name: narok
plugins:
  - solidity
  - hardhat
  - base
contracts_folder: contracts
dependencies:
  - name: openzeppelin-contracts
    local: ./lib/openzeppelin-contracts
solidity:
  version: "0.8.25"
  import_remapping:
    - "@openzeppelin/contracts/=openzeppelin-contracts"
providers:
  http:
    base:
      mainnet:
        uri: ${BASE_RPC_URL}
